/// Flutter icons AppIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String? _kFontPkg = null;

  static const IconData add = IconData(0xe800, fontFamily: _kFontFam,);
  static const IconData calories = IconData(0xe801, fontFamily: _kFontFam,);
  static const IconData cancel = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData check = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData co2 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData creativity = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData education = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData energy = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData environment = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData explore = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData garbage = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData social = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData statistics = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
